# Generated by Django 4.1.2 on 2022-12-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0016_carrito_item_stock_carrito_item_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
