# Generated by Django 5.0.3 on 2024-03-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0019_alter_carrito_total_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='imagen',
        ),
    ]
