# Generated by Django 4.1.1 on 2022-12-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0015_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_item',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrito_item',
            name='subtotal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrito_item',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
